name: Synth Test
run-name: Synth Test [${{ github.head_ref || github.ref_name }}] triggered by [${{ github.event_name }}/${{ github.actor }}]

on:
  push:
  pull_request:
    branches: 'main'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  synth-test:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: Checkout Repository [${{ github.head_ref || github.ref_name }}]
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Run Synth Test for [${{ github.head_ref || github.ref_name }}]
        run: npm run synth
        env:
          CDK_DEFAULT_ACCOUNT: "123456789012"
          CDK_DEFAULT_REGION: "us-east-1"
          STAGE: "Alpha"